name: Build and deploy preview

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: ./.github/workflows/build.yml
      - name: Build docs site
        run: yarn build:site
      - name: Build Storybook (preview)
        run: yarn workspace @spectrum-css/preview build
      - name: Move Storybook build to dist
        run: yarn postbuild:all
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: "dist"
          production-branch: "main"
          production-deploy: false
          netlify-config-path: ./netlify.toml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ github.event.pull_request.title }}
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: true
          alias: pr-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_GH_ACTIONS_DEPLOY }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10
