name: Visual regression testing

on:
  pull_request:
    types: [labeled]
    # paths:
    #   - 'components/**/*'
    #   - 'tools/preview/**/*'

jobs:
  build:
    if: github.event.label.name === "run_vrt"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Use Node LTS version
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: Install dependencies
        run: yarn install
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          dryRun: true
          storybookBaseDir: tools/preview
          exitOnceUploaded: true
          onlyChanged: true
          traceChanged: true
          diagnostics: true
          # forces a pass but doesn't run
          skip: true #${{ github.event.pull_request.draft == true }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: chromatic-build-artifacts-${{ github.run_id }}
          path: |
            tools/preview/chromatic-diagnostics.json
            **/build-storybook.log
